FROM rust:1.95 AS builder

WORKDIR /workspace
COPY Cargo.toml Cargo.lock ./
COPY backend/Cargo.toml backend/Cargo.toml
COPY backend/src backend/src
COPY crates/dormtk-api-types/Cargo.toml crates/dormtk-api-types/Cargo.toml
COPY crates/dormtk-api-types/src crates/dormtk-api-types/src
COPY crates/dormtk-core/Cargo.toml crates/dormtk-core/Cargo.toml
COPY crates/dormtk-core/src crates/dormtk-core/src

RUN cargo build --release -p dormtk-backend

# 生产镜像
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.8

WORKDIR /app

COPY --from=builder /workspace/target/release/dormtk-backend ./

USER 1000

EXPOSE 8080

CMD ["./dormtk-backend"]
